class RrToRspecConverter::TextTransformer
  public

  def transform: () -> String

  private

  def initialize: (String content, ?RrToRspecConverter::TextTransformerOptions options) -> void

  def line_indent: (Astrolabe::Node node) -> String

  def log: (String str) -> void

  def range: (Integer start_pos, Integer end_pos) -> Parser::Source::Range

  def remove_never_node: (Astrolabe::Node node) -> bool
end

module Parser
  module Source
    class Range
    end
  end
end

module Astrolabe
  class Node
  end
end
